# Site settings
title: "The art of Kotlin"
email: patriknygren82@gmail.com
description: "The place I collect my thoughts around software development and tools."
baseurl: ""
url: "https://patriques82.github.io"
title_description: "This is the place where I collect my thoughts around software development and tools. I mostly focus on Kotlin, and web."
title_image: "https://avatars.githubusercontent.com/patriques82"
google_analytics:
disqus_account:
github_repository: https://github.com/patriques82/patriques82.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username:
github_username:  patriques82
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/patrik-nygren-7788a626/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left:
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
